#!/usr/bin/env python3
"""fsp-ref conformance adapter. See conformance/ADAPTER.md."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from fsp.adapter import main  # noqa: E402

sys.exit(main())
